name: Build and deploy dotnet core app to Azure Function App - function-footy

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  DOTNET_VERSION: '10.0.x'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v6

      - name: Setup DotNet ${{ env.DOTNET_VERSION }} Environment
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: 'Resolve Project Dependencies Using Dotnet'
        run: dotnet publish --configuration Release --output ./output
      
      - name: 'Run Azure Functions Action'
        uses: Azure/functions-action@v1
        id: fa
        with:
          app-name: 'function-footy'
          package: './output'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_5D89D648720D469CB3BD06ABE08F7EFF }}